//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MyObjectInfo
{
    [Serializable]
    public class ObjectInfoMsg : Message
    {
        public const string k_RosMessageName = "my_object_info_msgs/ObjectInfo";
        public override string RosMessageName => k_RosMessageName;

        // ObjectInfo.msg
        public string object_name;
        public int object_id;
        public double object_pos_x;
        public double object_pos_y;
        public double object_pos_z;
        public double object_width;
        public double object_height;

        public ObjectInfoMsg()
        {
            this.object_name = "";
            this.object_id = 0;
            this.object_pos_x = 0.0;
            this.object_pos_y = 0.0;
            this.object_pos_z = 0.0;
            this.object_width = 0.0;
            this.object_height = 0.0;
        }

        public ObjectInfoMsg(string object_name, int object_id, double object_pos_x, double object_pos_y, double object_pos_z, double object_width, double object_height)
        {
            this.object_name = object_name;
            this.object_id = object_id;
            this.object_pos_x = object_pos_x;
            this.object_pos_y = object_pos_y;
            this.object_pos_z = object_pos_z;
            this.object_width = object_width;
            this.object_height = object_height;
        }

        public static ObjectInfoMsg Deserialize(MessageDeserializer deserializer) => new ObjectInfoMsg(deserializer);

        private ObjectInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.object_name);
            deserializer.Read(out this.object_id);
            deserializer.Read(out this.object_pos_x);
            deserializer.Read(out this.object_pos_y);
            deserializer.Read(out this.object_pos_z);
            deserializer.Read(out this.object_width);
            deserializer.Read(out this.object_height);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.object_name);
            serializer.Write(this.object_id);
            serializer.Write(this.object_pos_x);
            serializer.Write(this.object_pos_y);
            serializer.Write(this.object_pos_z);
            serializer.Write(this.object_width);
            serializer.Write(this.object_height);
        }

        public override string ToString()
        {
            return "ObjectInfoMsg: " +
            "\nobject_name: " + object_name.ToString() +
            "\nobject_id: " + object_id.ToString() +
            "\nobject_pos_x: " + object_pos_x.ToString() +
            "\nobject_pos_y: " + object_pos_y.ToString() +
            "\nobject_pos_z: " + object_pos_z.ToString() +
            "\nobject_width: " + object_width.ToString() +
            "\nobject_height: " + object_height.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
